import type { Metadata } from "next";
import MarketingFooter from "@/features/marketing/components/MarketingFooter";
import MarketingNav from "@/features/marketing/components/MarketingNav";

export const metadata: Metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="bg-lp-cream">
      <MarketingNav />
      <article className="mx-auto w-full max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-bold tracking-tight text-lp-ink">Terms of Service</h1>
        <p className="mt-2 text-sm text-stone-500">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="prose-legal mt-8 space-y-6 text-sm leading-relaxed text-stone-600">
          <section>
            <h2 className="text-lg font-semibold text-lp-ink">1. What LandPilot is</h2>
            <p className="mt-2">
              LandPilot is a software tool that analyzes publicly available and user-provided data about a
              parcel of land and produces an informational score, risk assessment, and narrative summary. It is a
              decision-support tool, not a substitute for professional due diligence.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-lp-ink">2. Not financial, legal, or investment advice</h2>
            <p className="mt-2">
              Nothing produced by LandPilot — including scores, risk levels, recommendations (&quot;Strong Buy,&quot;
              &quot;Buy,&quot; &quot;Consider,&quot; &quot;Pass&quot;), ROI projections, or AI-generated narrative content — constitutes financial,
              legal, tax, or professional investment advice. Some figures are estimates or documented defaults used
              when real data isn&apos;t available, and some content is generated by AI models that can be wrong or
              incomplete. You are solely responsible for verifying all information and for your investment
              decisions. Consult a licensed real estate agent, attorney, financial advisor, or other relevant
              professional before buying, selling, or developing land.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-lp-ink">3. Accounts</h2>
            <p className="mt-2">
              You&apos;re responsible for maintaining the security of your account and for all activity under it.
              You must provide accurate information when registering.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-lp-ink">4. Subscriptions and billing</h2>
            <p className="mt-2">
              Paid plans are billed in advance on a recurring basis through our payment processor (Stripe). You can
              cancel at any time through your account settings; your plan remains active until the end of the
              current billing period. We don&apos;t store your payment card details — Stripe handles all payment
              processing.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-lp-ink">5. No warranty</h2>
            <p className="mt-2">
              LandPilot is provided &quot;as is&quot; without warranties of any kind, express or implied, including
              accuracy, completeness, or fitness for a particular purpose. Data sources (government APIs, AI
              models, third-party services) can be incomplete, outdated, or unavailable.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-lp-ink">6. Limitation of liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, LandPilot and its operators are not liable for any
              investment losses, damages, or decisions made based on information from the platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-lp-ink">7. Changes</h2>
            <p className="mt-2">
              We may update these terms as the product evolves. Continued use of LandPilot after a change means
              you accept the updated terms.
            </p>
          </section>

          <p className="border-t border-lp-border pt-6 text-xs text-stone-400">
            This is a general-purpose template and not a substitute for legal advice. Review with a qualified
            attorney before relying on it for a live product handling real user payments.
          </p>
        </div>
      </article>
      <MarketingFooter />
    </div>
  );
}
